### ISSUE TITLE
Object detection algorithm

### ISSUE THREAD

**Issue by Supernova1114** [SaddlebackCollegeRobotics/.github#10]
[URC 2024 Rules](https://drive.google.com/file/d/1Y_lltxyXzpqOE1q90gFQ-IBEvniJOQxL/view)
In this year's autonomy mission, there are requirements for object detection other than Aruco tags.
We will need to detect an orange mallet, and a plastic reusable water bottle.
You can find specific in the rules including a link to the mallet item.

- [x] Write description of plan for training, frameworks used, etc.
- [x] Test prebuilt model.
- [x] Train model for mallet detection.
- [x] Train model for water bottle detection.
- [ ] Get model working with Isaac ROS object detection??

**Comment by Supernova1114** [comment]
Some object detection libs:
- https://github.com/google/mediapipe
- OpenCV
- ZED sdk
- Yolo v8

**Comment by Supernova1114** [comment]
Update: 
- Nvidia has object detection packages in the Isaac ROS library. Support for Yolov8 and detectnet model.
- Support for ROS
- Hardware accelerated
- https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_object_detection

**Comment by Supernova1114** [comment]
ToDo:
- [x] Order orange mallet
- [x] Order extra water bottles / colors for training.

**Comment by Supernova1114** [comment]
Doing research:
- https://www.amazon.com/s?k=32+oz+water+bottles&crid=39JBB2NLSMH04&sprefix=32+oz+water+bottle%2Caps%2C139&ref=nb_sb_noss_1
- https://www.kaggle.com/code/abdallahwagih/bottle-synthetic-classification-acc-99
- https://www.youtube.com/watch?v=m9fH9OWn8YM
- https://www.kaggle.com/code/abdallahwagih/water-bottle-efficientnetb3-85-71
- https://storage.googleapis.com/openimages/web/index.html

**Comment by kavehzare98** [comment]
Progress Report:
- We have a working model that can identify most objects (specifically bottles) based on camera feed.
- Current issue: pre-trained model cannot identify hammers or the orange mallet.
- Able to calculate distance, but error grows with distance. Planning on using a distortion matrix to reduce error plus using a camera with a known focal length. (1/12/24)
- **LATEST UPDATE (1/21)**: Trained model on 1900 annotated images of orange mallet (with few bottle annotations). ~4500 images post-augmentation. Using Google Colab's A100 GPU. Able to use 0.7 confidence with approx. 80-90% precision. Current training duration: 2 hours
- 389/500 compute units left on Colab with subscription

Things To Do:

- [x]  Gather our own images on Saturday, January 13th, 2024 for the orange mallet (10,000 images) and water bottles (5,000 images).
- [x] Annotate our dataset via Roboflow by January 16th.
- [x] Train model on custom dataset on Google Colab
- [ ] Test model on orange mallet and Nalgene bottles in appropriate environment using ZED
- [ ] Configure Object's distance from rover via bounding boxes and frame coordinates
- [ ] ROSify and test on rover
- [ ] (Optional) Configure obstacle avoidance
- [ ] Looking into Ensemble where we get to simultaneously use two separately trained models for bottles and mallet.

**Comment by kavehzare98** [comment]
Configuring Object's distance from sensor (camera) - current research:

- https://stackoverflow.com/questions/14038002/opencv-how-to-calculate-distance-between-camera-and-object-using-image

- https://github.com/opencv/opencv/blob/4.x/samples/python/calibrate.py

- https://www.geeksforgeeks.org/realtime-distance-estimation-using-opencv-python/

- https://pyimagesearch.com/2015/01/19/find-distance-camera-objectmarker-using-python-opencv/

Formula Used to Find Distance:

- F = (P x D) / W    =>   Solve for D' = (F x W) / P

> F is the Focal Length of Camera

> measure the apparent width in pixels P

> distance D from our camera

> a marker or object with a known width W

**Comment by Supernova1114** [comment]
Labeling is in progress.

**Comment by Supernova1114** [comment]
Object detection implementation is done, including a distance estimator.
