### ISSUE TITLE
Valk's hardware & autonomy system

### ISSUE THREAD

**Issue by jasperdoan** [SaddlebackCollegeRobotics/.github#102]
# [Full doc](https://github.com/SC-Robotics-2021/SCR_2022-23/blob/master/Autonomy/AUTONOMY.md)

**Comment by theunkn0wn1** [comment]
the two systems are not directly compatible, you would need to build a bridge that translates the gRPC calls into Osiris's ROS2 infra and back again if you want to use any of Valkyrie's old gRPC C2 infrastructure

**Comment by theunkn0wn1** [comment]
alternatively, if the team is more comfortable using ROS2 for the entire thing, you can probably replace the Valkyrie gRPC C2 components while preserving the underlying control firmware.
you would need to adapt the existing C2 -> drivedrain ecu controller code to fit in Osiris's system

**Comment by jasperdoan** [comment]
Sounds good, we will look into this

**Comment by theunkn0wn1** [comment]
feel free to ask questions if the team needs any help understanding how valkyrie's software&firmware were put together.
I will be of limited use as it relates to ROS2 specifically, but i did design valkyrie's C2 from scratch.
