### ISSUE TITLE
Acceleration / Deceleration

### ISSUE THREAD

**Issue by Supernova1114** [SaddlebackCollegeRobotics/.github#117]
Implement acceleration and deceleration for drive motors. 
Make some variables easily accessible as constants to be able to change accel / decel.

**Comment by jasperdoan** [comment]
We running out of time for this. @mcdipples is and has been inactive so, I suggest removing her as the assignees and move on with another plan in mind

**Comment by jasperdoan** [comment]
Closed, no longer a concern
