### ISSUE TITLE
Get RTK GNSS Modules working.

### ISSUE THREAD

**Issue by Supernova1114** [SaddlebackCollegeRobotics/.github#129]
Using the U-Blox python library.

**Comment by devloos** [comment]
- [x] Get the script running getting longitude and latitude
- [x] get RTK (real-time kinematics)

### Resources
- https://github.com/sparkfun/Qwiic_GPS-RTK2/tree/master
- https://learn.sparkfun.com/tutorials/gps-rtk2-hookup-guide
- https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library
- https://blog.emlid.com/introduction-to-rtk-gps/
- https://github.com/sparkfun/Qwiic_Ublox_Gps_Py

### New Stuff
- https://www.sparkfun.com/products/15136
- https://learn.sparkfun.com/tutorials/sparkfun-gps-rtk-dead-reckoning-zed-f9r-hookup-guide/python-example-code
- https://www.u-blox.com/en/product/zed-f9p-module
- https://content.u-blox.com/sites/default/files/ZED-F9P-04B_DataSheet_UBX-21044850.pdf
- https://www.u-blox.com/en/technologies/high-precision-positioning
- https://www.u-blox.com/en/press-releases/u-blox-announces-u-blox-f9-robust-and-versatile-high-precision-positioning-technology
- https://learn.sparkfun.com/tutorials/gps-rtk2-hookup-guide/all
- https://learn.sparkfun.com/tutorials/how-to-build-a-diy-gnss-reference-station
- https://learn.sparkfun.com/tutorials/how-to-upgrade-firmware-of-a-u-blox-gnss-receiver

**Comment by Supernova1114** [comment]
Looks like you can get the RTK surveyor working via either a Windows application, or an arduino.
Should still be able to enable surveying and the such on a normal PC with code?????

**Comment by Supernova1114** [comment]
RTK working very well with 10 minute survey.

**Comment by Supernova1114** [comment]
https://content.u-blox.com/sites/default/files/documents/ZED-F9P-MovingBase_AppNote_UBX-19009093.pdf
