### ISSUE TITLE
Design control schema for drive.

### ISSUE THREAD

**Issue by Supernova1114** [SaddlebackCollegeRobotics/.github#134]
A design listing what features we want for drive control:
- What buttons on the gamepad do what?
- What features do we want? Ex: Cruise control, safety shut-off, acceleration control?
- We are not locked to the number of buttons on the gamepad, you can use certain buttons as function buttons.

**Comment by Sam-Nasri** [comment]
- Safety shut-off: A combination of buttons that makes the motors go idle
- Cruise control
- Toggle between different setups for different missions
- Rumbling in controller when going over rough terrain
- Alternative option for turning the rover
