### ISSUE TITLE
Web GUI Feature Design

### ISSUE THREAD

**Issue by Supernova1114** [SaddlebackCollegeRobotics/.github#136]
- [ ] Create a list of features that we want on the Web GUI. 
- [ ] Draft a drawing of the design with all the listed features.

**Comment by Supernova1114** [comment]
Some examples: 
- Video feed
- Command console

**Comment by Sam-Nasri** [comment]
- Video feed of the rover: from the zed
- Watchdog status: is he starving or not
- Command console
- GPS map
- Live Lidar scans
- Antenna signal strength
- Different feature setups/layouts for different missions

**Comment by Sam-Nasri** [comment]
General:

-  Battery level
- Drive speed
- Current
- Longitude and latitude 
- Heading 
- Distance traveled
- Military time clock
- Antenna signal strength

Arm:

- Visual model of the current position of the arm and its axis
- Retract the arm

Science:

- Sensor data
- Sensor visualization, i.e graphs

Autonomy:

- Bounding box for detected object
- Input for GPS coordinates
- Map height and waypoint visualization
- Rover position and ability to add points to map by clicking
- Box with a colour that is the same as the one on the rover that flashes when the rover arrives at a destination, drives autonomously, etc...
- Green pathfinding line from ROS navigation stack

**Comment by devloos** [comment]
- Video feed of the rover
  - Feed from zed
  - Arm cameras
- Watchdog status
  - We will probably need 10
  - Should we have the ability to reset?
- Command console
  - is there a library
  - lets restrict some commands
- GPS map
  - something like boat GPS system
  - ![Image](https://github.com/SaddlebackCollegeRobotics/.github/assets/58356571/8fb0d0f5-92ba-4ea5-85f4-6830d0455789)
- Live Lidar scans
  - can I integrate this with gps
  - I should search for a library
- Different feature setups/layouts for different missions
