### ISSUE TITLE
Docker image for drive.

### ISSUE THREAD

**Issue by Supernova1114** [SaddlebackCollegeRobotics/.github#137]
Drive code does not build on Jetson. Need docker image with ROS 2 Humble and Ubuntu 22.04

**Comment by Terracom12** [comment]
# Resources
Using [jetson-containers](https://github.com/dusty-nv/jetson-containers), which provides a set of docker images \(Packages\) specifically for NVIDIA Jetson devices, along with scripts to configure said packages.

[This guide](https://github.com/dusty-nv/jetson-containers/blob/master/docs/run.md) outlines how to run a (set of) package(s) using the script [run.sh](https://github.com/dusty-nv/jetson-containers/blob/master/run.sh). Another useful script provided is [autotag](https://github.com/dusty-nv/jetson-containers/blob/master/autotag), which provides away to locate a docker container based on a generic argument. (i.e. `./autotag ros` will output the full name of the relevant ros container).

The method I used to get the image up-and-running **quickly** was by running:

```
./run.sh --volume /home/orin/workspaces/drive_2023_24:/drive_2023_24  $(./autotag ros)
                  ^                                            
                  +-- Mounts the local drive_2023_24 repo onto the container      
                  
```

This is quite a verbose command, and given that I have very little knowledge of ROS or Docker at this time, I highly recommend that this be updated in the near future. For now, though, this seems to be a working solution.
