### ISSUE TITLE
Add Arm and Drive Precision Mode

### ISSUE THREAD

**Issue by Supernova1114** [SaddlebackCollegeRobotics/.github#194]
While a button is pressed on the gamepad, reduce maximum motor speed.
This enables precise control of the arm and drive system.

**Comment by justinele19** [comment]
# Add Arm and Drive Precision Mode 
(purple controller is drive, green controller is arm)

## Button Descriptions 
* right bumper: safety button for drive
* right trigger: go button for drive
* left bumper: nothing 
* left trigger: nothing for arm, something for drive 

## PLAN - left bumper for precision button 

### Notes on gamepad_input.py
* deadzone - the area around thumb stick controller that doesn't respond to movement
  * the higher the deadzone, the larger the area of the deadzone (need to move the joystick a farther distance to be able to move)

**Comment by Supernova1114** [comment]
Justine implemented precision mode for arm system.
She will be working on the same for the drive system.

**Comment by Supernova1114** [comment]
Update:
- Justine implemented precision mode for drive.
