### ISSUE TITLE
Write simple ROS Package for Drive System

### ISSUE THREAD

**Issue by Supernova1114** [SaddlebackCollegeRobotics/.github#2]
- [x] Write simple ROS package

**Comment by devloos** [comment]
This will be fun!

**Comment by Supernova1114** [comment]
Simple ROS package is written.
Need to begin implementing the recently created ROS graph design.

**Comment by Supernova1114** [comment]
Fix issues:
- [ ] When launch file starts, will not wait for CAN bus to exist or to be up and running before initializing drive nodes.
- [ ]
