### ISSUE TITLE
Research ROSBoard

### ISSUE THREAD

**Issue by Supernova1114** [SaddlebackCollegeRobotics/.github#4]
https://github.com/dheera/rosboard

Research and write down main features of this data visualization platform.

Some example points to find:
- Does it have ROS2 support?
- What OS are supported?
- Can it be hosted as a web GUI / used on mobile devices for viewing on the go?
- Does it support video streams?
- What types of data are supported?
- Can you save the current data layout as a template?
- Any other cool/interesting features you find.

**Comment by jmejias0** [comment]
Here are the links where I got the information that I'm highlighting:

https://github.com/kiwicampus/rosboard
https://github.com/kiwicampus/rosboard_client (library)

Does it have ROS2 support?
- ROS1/ROS2 compatible. This package will work in either ROS 1 or 2 versions.

Can it be hosted as a web GUI / used on mobile devices for viewing on the go?

- Mobile friendly. Designed so you can walk around next to your robot with a phone while viewing ROS topics. (ROSboard)

-  Connecting a local ROS2 system to a remote one using a VPN like [Husarnet](https://husarnet.com/docs/tutorial-ros2). This removes the possibility of selecting only some topics for transmission and does not perform any compression of the data, which makes it unsuitable for robots running high data rate sensors like cameras and LIDAR and relying on a cellular connection to stream the data. (ROSboard client)

Does it support video streams?

- This package includes a graphical user interface (GUI) that can be used to connect the local computer (client) to the server. The GUI allows a user to define which topics will be streamed from the server to the client and vice versa. In addition to such capability, the interface presents information related to the rate at which the topic messages are received and the latency of them i.e. the time difference between the message header stamp and the current system time. Finally, some general metrics are presented regarding the CPU usage, average roundtrip time (RTT), and current download speed. This application is intended to ease the streaming process while being capable of dynamically selecting which topics are streamed. (ROSboard client)

What types of data are supported?

- The main objective of this library is to selectively stream ROS topics using websockets from a remote robot to a local machine, allowing to use visualization tools like rviz, rqt, mapviz, etc on live data transmitted over the internet. The library implements a client to use with a [rosboard](https://github.com/kiwicampus/rosboard) server running in the remote robot. (Rosboard client) 
- However rosboard has a web based UI that shows each message in a different widget, which makes it harder to understand complex navigation data like pointclouds and costmaps. 
- Does not allow to interact with 3D data or to change the tf frame in which it is shown.
-  A ROS GUI similar to rosboard’s web GUI. It allows people to see all the available topics on the server and interactively subscribe/unsubscribe to them. When subscribed to a topic, the received data gets republished as ROS messages on the local machine, allowing people to use the desktop viz toolchain that everyone is already so familiar with.

Can you save the current data layout as a template?
-  Haven't find anything yet.

Any other cool/interesting features you find.
- rviz
- Rosbridge aims to provide all the communication capabilities you would expect from two ROS systems running on the same network (topics, services, action servers), which go beyond what we needed.

https://discourse.ros.org/t/introducing-rosboard-client/27068/6

https://github.com/dheera/rosshow/

https://github.com/kiwicampus/rosboard_client

https://github.com/kiwicampus/rosboard

https://github.com/kiwicampus/rosboard_client

https://github.com/RobotWebTools/rosbridge_suite
