### ISSUE TITLE
Research open source NASA interface.

### ISSUE THREAD

**Issue by Supernova1114** [SaddlebackCollegeRobotics/.github#5]
https://github.com/nasa/openmct

Research and write down main features of this data visualization platform.

Some example points to find:
- Does it have ROS2 support?
- What OS are supported?
- Can it be hosted as a web GUI / used on mobile devices for viewing on the go?
- Does it support video streams?
- What types of data are supported?
- Can you save the current data layout as a template?
- Any other cool/interesting features you find.

**Comment by Sam-Nasri** [comment]
- Couldn't find anything related to ROS2.
- Says that it is a "mission control framework for visualization on desktop and mobile devices." So yes, it can be used on mobile devices. 
- Implies that a wide range of OS are supported, but doesn't mention which ones.
- Supports the following browsers; Firefox ESR, last two versions of chrome, unreleased chrome versions, IOS Safari/Safari 16 and later.
- Project uses nvm
- Doesn't contain video based plugins. However, it does mention that the Web Page Plugin can be utilized to display videos by "taking a url (could be where the video is hosted) and will plug it into an iframe. "
- Supports basic "Telemetry"  which is referring to incoming time-series data (historical or realtime/streaming) of varying types, images, and can also be extended to support other types of data like geospatial data via plugins
