### ISSUE TITLE
5 GHz setup antenna

### ISSUE THREAD

**Issue by jasperdoan** [SaddlebackCollegeRobotics/.github#72]

**Comment by austinlucaslake** [comment]
No more memes on in the documentation please. All the information should be clear and concise.

**Comment by jasperdoan** [comment]
[isaac_ros_compression](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_compression)

**Comment by jasperdoan** [comment]
![Image](https://user-images.githubusercontent.com/49565505/220183994-851fd6f2-d93f-4f35-86c5-d3b1a6267dbf.png)
