### ISSUE TITLE
Test Zed2i Global Heading

### ISSUE THREAD

**Issue by Supernova1114** [SaddlebackCollegeRobotics/.github#98]
The Zed2i stereo camera has a magnetometer.

Would like to test how accurate it's global heading is.
Does this require VSLAM?

https://www.stereolabs.com/docs/sensors/magnetometer/

Refer to #95

**Comment by jahaniskhan** [comment]
demolished this project, calibrated the zed, received live data in terms of rotation and respect to the accuracy. On the think pad, calibration dat is stored :) . Repository of experimental has updated code :)
